server:
  port: 8080
spring:
  application:
    name: "apicreditos"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27018/creditos"
    rabbitmq:
      host: "localhost"
      username: "guest"
      password: "guest"
      virtual_host: /
      port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
